language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules
env:
  global:
  - secure: "TbRrWsjlkd4DQHJzf20jcpJd/JER+S6dk8K+ozaDoAtatIviicGlGa4N7kz914AyteqZGe5BfQZbfqDYDepENGoiIN5PmAXUVzXxUz+urgk/AyLLkIkUcAAF/wLZJQxEzP7UAwOAlJwIcaxLGnyf0sy06m7TxK+gYH1HhiEuzHP090yVdtxS+wSlxlRifAmKiVHaVAu07nempTp/ogMtNUNJyAmo3Q3Txw9iUgG0b5oaQLeKGON6KP2yAlCc2Sr9N8Spfdl24HKLn3RrLeYl7dGkY1l3zNXHduaGaUdmUTCawozD4cOynkJiUVifG/Vvk5A1Uu9KeCg6WP4wXfoKo4ilsUKFbIr7ToWNXnLdSiswVeKHXlKRA70BoejpOB0+6fjKFTx9EtZMrps8NjbO0K5ahGGmyHP5gE207WwNm5R8uwZax2RDRO2oddWGwoDjl4Hx4Ogwk05wVa0n9sbc8ywMdfF4LZEyst70z/P1EyVOgOwhPB/1+1A1L2H6XN+HNAq7vWZxr+7vFl4zoeL1kA/+xtpEJhXbnhbF36zYQCM0BB/t/3pP2Tmm6T4M41D7c81sVW1JXOUnpTHCAxrlSIuELvNNmg71waqM7rnQSW75iFDR+A6Pb4nEWnHjQLnh+C+CVX2j1//YdpNfbSKRT2XexgymjBhaY/qK9oSXOSU="
script:
- yarn add cozy-app-publish
- yarn cozy-app-publish --travis --editor Cozy --token $REGISTRY_TOKEN --build-dir '.' --on-branch build
