language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
branches:
  except:
  - build
env:
  global:
  - CXX=g++-4.8
  - secure: EaUy9WNQWQqRQPx+sNAXmSXIYm+CHiaysTjem89I/u9Fdk/1Ww5hrWvu88zNsEsn4iH84gyomRj852xiZVt+ETz1dJHRgJwkOET3DRLRGQdd8xzAEUoQ62d+7x/SXvcCTzQR3YGTbNvvRByXqF0i9YAy7awVff060JhQEn3hZmWtQTWoPX8Zqu7G3HhlI3YUw8rF6hKey4mLWLdCUr4UzQ4HXsKQfACrCK4CkEtonbsW5InJ4Bw8F1nffJBuAJPvDH0ZhyJG8vUXYjBxsq6MtJfRLIgGrUIdZEz8HRirTm/G/usiHnf0TJkX3eSwM2mOdKkgP+hGoFXGQtGZhsMdDT4UOTHmsE/9VUknqR+71IMFFV4GpfkqyVOrN/qsfM2cui6cyBfZskmOJ2VQckgNEF8YrY8StnPIO3bsadeH7byBD6CCiU0LYEaFuyjNUOgloh+bSI5euYyjsTGB7voFwJUhcyBg0knM8W0JAp6b0Fx4lq5GXjx2q4fDg6oTQkDcxk38wz6auGc/8wDLSi+mNkwkQbjEDeLXvFe92g+exzlfN64CFToKnci3Sx/4h1YT4GCwfia/++Hp4m5DSW9cSFanjDTAY2v29rLzZFP3XP5zuiKPrCQYIaEa7NN04WQpaMcac0iyWV5sOIPs6QJZCTpeO2w+KhxsRxJSDjHUX9k=
script:
  - yarn
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    - deadsnakes
    packages:
    - g++-4.8
    - python3.5
    - pngquant
cache:
  yarn: true
  directories:
  - node_modules
deploy:
- provider: script
  repo: konnectors/cozy-konnector-trainline
  skip-cleanup: true
  script: yarn build && pngquant build/screenshots/* -f --ext ".png" && yarn run deploy:travis
  on:
    branch: master
- provider: script
  repo: konnectors/cozy-konnector-trainline
  skip-cleanup: true
  script: yarn add cozy-app-publish && yarn cozy-app-publish --token $REGISTRY_TOKEN --build-dir '.'
  on:
    branch: build
